### ISSUE TITLE
Hyperparameter for pretrain

### ISSUE THREAD

**Issue by jyFengGoGo** [ayumiymk/DiG#2]
The parameters setting given for pretrain are loss_weight_contrast=0.1 and loss_weight_pixel=1. But the setting was opposite in paper which were loss_weight_contrast=1 and loss_weight_pixel=0.1. Which pair should I use if I want to reimplement the pretrain of vit-small by myself?
Thank you.

**Comment by ayumiymk** [comment]
I have checked the paper. I am sorry that it is a typo. Please refer to this repo.

**Comment by jyFengGoGo** [comment]
> I have checked the paper. I am sorry that it is a typo. Please refer to this repo.

Got it, thanks!
